#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  Apr 15, 2022 07:08:59 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 800x581+560+240
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 7444 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "TTW PTcloner"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 580 -width 800 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    labelframe $site_3_0.lab48 \
        -font TkDefaultFont -foreground black -text From \
        -background $vTcl(actual_gui_bg) -height 400 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 380 
    vTcl:DefineAlias "$site_3_0.lab48" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab48
    button $site_4_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_from -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Browse 
    vTcl:DefineAlias "$site_4_0.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_4_0.lab52 \
        -font TkDefaultFont -foreground black -text {Save file path} \
        -background $vTcl(actual_gui_bg) -height 55 -width 350 
    vTcl:DefineAlias "$site_4_0.lab52" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab52
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black \
        -state readonly -textvariable text_save_from -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab55 \
        -font TkDefaultFont -foreground black -text Name \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab55" "Labelframe2_2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab55
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_name_from \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab57 \
        -font TkDefaultFont -foreground black -text Level \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab57" "Labelframe2_2_2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab57
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_level_from \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab59 \
        -font TkDefaultFont -foreground black -text {First class} \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab59" "Labelframe2_2_2_1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab59
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_class_from \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab60 \
        -font TkDefaultFont -foreground black -text {Second class} \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab60" "Labelframe2_2_2_1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab60
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly \
        -textvariable text_second_class_from -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_2_1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 15 -y 20 -width 350 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 15 -y 90 -width 350 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 15 -y 150 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 15 -y 210 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 15 -y 270 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab60 \
        -in $site_4_0 -x 15 -y 330 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab61 \
        -font TkDefaultFont -foreground black -text To \
        -background $vTcl(actual_gui_bg) -height 400 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 380 
    vTcl:DefineAlias "$site_3_0.lab61" "Labelframe1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab61
    button $site_4_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command open_to -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Browse 
    vTcl:DefineAlias "$site_4_0.but50" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_4_0.lab52 \
        -font TkDefaultFont -foreground black -text {Save file path} \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab52" "Labelframe2_1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab52
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_save_to \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab55 \
        -font TkDefaultFont -foreground black -text Name \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab55" "Labelframe2_2_1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab55
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_name_to \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab57 \
        -font TkDefaultFont -foreground black -text Level \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab57" "Labelframe2_2_2_2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab57
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_level_to \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_2_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab59 \
        -font TkDefaultFont -foreground black -text {First class} \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab59" "Labelframe2_2_2_1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab59
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly -textvariable text_class_to \
        -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_2_1_2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_4_0.lab60 \
        -font TkDefaultFont -foreground black -text {Second class} \
        -background $vTcl(actual_gui_bg) -height 55 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$site_4_0.lab60" "Labelframe2_2_2_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab60
    entry $site_5_0.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -state readonly \
        -textvariable text_second_class_to -width 324 
    vTcl:DefineAlias "$site_5_0.ent53" "Entry1_2_2_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent53 \
        -in $site_5_0 -x 10 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 15 -y 20 -width 350 -relwidth 0 -height 60 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 15 -y 90 -width 350 -relwidth 0 -height 55 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 15 -y 150 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab57 \
        -in $site_4_0 -x 15 -y 210 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 15 -y 270 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab60 \
        -in $site_4_0 -x 15 -y 330 -width 350 -height 55 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra62 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 155 -width 785 
    vTcl:DefineAlias "$site_3_0.fra62" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra62
    button $site_4_0.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command proceed -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -state disabled -text Proceed 
    vTcl:DefineAlias "$site_4_0.but63" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab65 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text {Waiting ...} 
    vTcl:DefineAlias "$site_4_0.lab65" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but63 \
        -in $site_4_0 -x 10 -y 10 -width 767 -relwidth 0 -height 94 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 350 -y 120 -width 199 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 10 -width 380 -relwidth 0 -height 400 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 410 -y 10 -width 380 -height 400 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra62 \
        -in $site_3_0 -x 10 -y 420 -width 785 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -width 800 -relwidth 0 -height 580 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

